import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import ThemeCon from "./components/ThemeCon";
import { ClerkProvider } from "@clerk/nextjs";
// import Navbar from "@/components/Navbar";
// import SearchBox from "@/components/SearchBox";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <ThemeCon>
            <Header />
            {/* <Navbar /> */}
            {/* <SearchBox /> */}
            {children}
          </ThemeCon>
        </body>
      </html>
    </ClerkProvider>
  );
}
